Add extra test byKeysIncludeDocsFalse
Attempting to call getDocs() for a view with
include_docs=false raises the exception
java.lang.IllegalStateException: Cannot getDocs()
when include_docs is false.

This is because views can't return the same
"sparse" information that _all_docs can
return (id/rev/deleted).