Allow retrieval of deleted flag on all_docs (#439)
* Allow retrieval of deleted flag on all_docs

Introduce "sparse document" information which can be retrieved even
when include_docs=false is set. This allows for retrieval of id, rev,
and deleted flag.

Also, add null check to getDocsAs(): This ensures that attempting to
deserialise deleted documents does not prevent retrieval of
non-deleted ones.

* Update docs for AllDocsResponse

* Updated test for not excluding deleted in all_docs

* Add extra test byKeysIncludeDocsFalse

Attempting to call getDocs() for a view with
include_docs=false raises the exception
java.lang.IllegalStateException: Cannot getDocs()
when include_docs is false.

This is because views can't return the same
"sparse" information that _all_docs can
return (id/rev/deleted).

* Copyrights

* CHANGES